Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2020-08, with the labels that each got.

#269 Remove elastic charts dependency
  package.json
  yarn.lock
Labels: dependencies

#267 Improve error handling when retrieving all detectors
  public/pages/Dashboard/Container/DashboardOverview.tsx
  public/pages/DetectorsList/containers/List/List.tsx
  public/pages/DetectorsList/utils/constants.ts
  public/redux/reducers/ad.ts
  server/routes/ad.ts
Labels: enhancement

#277 fix wrong field name when preview
  server/routes/ad.ts
  server/routes/utils/__tests__/adHelpers.test.ts
  server/routes/utils/adHelpers.ts
Labels: bug

#278 support field search for detector simple filter
  public/pages/createDetector/components/DataFilters/SimpleFilter.tsx
Labels: enhancement

#273 Handle index not found error
  server/routes/ad.ts
  server/routes/utils/adHelpers.ts
Labels: bug fix

#279 Add UT for Detector List page
  public/pages/DetectorsList/components/EmptyMessage/EmptyMessage.tsx
  public/pages/DetectorsList/components/EmptyMessage/__tests__/EmptyMessage.test.tsx
  public/pages/DetectorsList/components/EmptyMessage/__tests__/__snapshots__/EmptyMessage.test.tsx.snap
  public/pages/DetectorsList/components/ListActions/__tests__/ListActions.test.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmDeleteDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/List/__tests__/List.test.tsx
  public/pages/DetectorsList/utils/__tests__/helpers.test.ts
  public/pages/DetectorsList/utils/__tests__/tableUtils.test.tsx
Labels: test

#284 parse types in fielddata
  public/redux/reducers/__tests__/mapper.test.ts
  public/redux/reducers/mapper.ts
Labels: bug

#283 Add intermediate callout message during cold start
  public/pages/DetectorDetail/containers/DetectorDetail.tsx
  public/pages/DetectorResults/containers/AnomalyResults.tsx
Labels: bug

#285 Add action item and message for init failue case due to invalid search query.
  public/pages/DetectorDetail/utils/constants.ts
Labels: enhancement

#286 Adding support for Kibana 7.9.0
  .github/workflows/CD.yml
  .github/workflows/e2e-tests-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  package.json
  public/app.js
  public/pages/AnomalyCharts/components/AlertsFlyout/__tests__/__snapshots__/AlertsFlyout.test.tsx.snap
  public/pages/DetectorConfig/containers/__mocks__/ui/chrome.js
  public/pages/DetectorResults/components/ListControls/__tests__/__snapshots__/ListControls.test.tsx.snap
  public/pages/DetectorsList/components/ListFilters/__tests__/__snapshots__/ListFilters.test.tsx.snap
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmDeleteDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmStartDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmStopDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/List/List.tsx
  public/pages/EditFeatures/components/AggregationSelector/__tests__/__snapshots__/AggregationSelector.test.tsx.snap
  public/pages/EditFeatures/components/CustomAggregation/__tests__/__snapshots__/CustomAggregation.test.tsx.snap
  public/pages/createDetector/components/DetectorInfo/__tests__/__snapshots__/DetectorInfo.test.tsx.snap
  public/pages/createDetector/containers/__tests__/__snapshots__/CreateDetector.test.tsx.snap
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana.release-notes-1.10.0.md
  yarn.lock
Labels: version upgrade

#293 Fix UT and remove lower EUI version dependency
  babel.config.js
  package.json
  public/pages/AnomalyCharts/components/AlertsFlyout/__tests__/__snapshots__/AlertsFlyout.test.tsx.snap
  public/pages/AnomalyCharts/components/AnomaliesStat/__tests__/__snapshots__/AnomalyStat.test.tsx.snap
  public/pages/DetectorDetail/components/ConfirmModal/__tests__/__snapshots__/ConfirmModal.test.tsx.snap
  public/pages/DetectorDetail/components/DetectorControls/__tests__/__snapshots__/DetectorControls.test.tsx.snap
  public/pages/DetectorResults/components/ListControls/__tests__/__snapshots__/ListControls.test.tsx.snap
  public/pages/DetectorsList/components/ListActions/__tests__/__snapshots__/ListActions.test.tsx.snap
  public/pages/DetectorsList/components/ListFilters/__tests__/__snapshots__/ListFilters.test.tsx.snap
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmDeleteDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmStartDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmStopDetectorsModal.test.tsx
  public/pages/createDetector/components/Datasource/__tests__/__snapshots__/IndexOption.test.tsx.snap
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.10.0.0.md
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana.release-notes-1.10.0.0.md
  release-notes/opendistro-for-elasticsearch.anomaly-detection-kibana-plugin.release-notes-1.7.0.0.md
  release-notes/opendistro-for-elasticsearch.anomaly-detection-kibana-plugin.release-notes-1.8.0.0.md
  release-notes/opendistro-for-elasticsearch.anomaly-detection-kibana-plugin.release-notes-1.9.0.0.md
  yarn.lock
Labels: test
