Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2020-07, with the labels that each got.

#252 Fix e2e test caused by new EuiComboBox added on CreateDetector page
  .cypress/integration/ad/workflow/create_detector.spec.ts
Labels: test

#248 Add missing feature alert if recent feature data is missing
  public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
  public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
  public/pages/DetectorResults/containers/AnomalyHistory.tsx
  public/pages/DetectorResults/containers/AnomalyResults.tsx
  public/pages/utils/anomalyResultUtils.ts
  public/utils/constants.ts
Labels: enhancement

#255 Automate release notes to unified standard
  .github/draft-release-notes-config.yml
Labels: documentation

#253 Add progress bar for initialization
  public/models/interfaces.ts
  public/pages/DetectorDetail/containers/DetectorDetail.tsx
  public/pages/DetectorDetail/utils/helpers.ts
  public/pages/DetectorResults/containers/AnomalyResults.tsx
  public/redux/reducers/ad.ts
  server/cluster/ad/adPlugin.ts
  server/routes/ad.ts
  server/routes/utils/adHelpers.ts
Labels: enhancement

#259 Update lodash dependency
  package.json
  yarn.lock
Labels: dependencies

#260 upgrade elastic chart; fix zoom in bug
  package.json
  public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
  public/pages/AnomalyCharts/containers/__tests__/AnomaliesChart.test.tsx
  yarn.lock
Labels: bug fix

#262 Add a few badges
  .github/workflows/unit-tests-workflow.yml
  README.md
Labels: documentation

#263 Add support for running CI with security
  .cypress/integration/ad/dashboard/ad_dashboard.spec.ts
  .cypress/integration/ad/detectorList/detector_list.spec.ts
  .cypress/support/commands.ts
  .github/configurations/docker-compose.yml
  .github/workflows/CD.yml
  .github/workflows/e2e-tests-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  README.md
  cypress.json
  package.json
Labels: test

#266 Upgrade Cypress and elliptic dependencies
  .github/workflows/e2e-tests-workflow.yml
  package.json
  yarn.lock
Labels: dependencies
