Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2020-10, with the labels that each got.

#310 Add category field to edit model configuration page
  public/models/interfaces.ts
  public/pages/DetectorConfig/components/AdditionalSettings/AdditionalSettings.tsx
  public/pages/DetectorConfig/containers/Features.tsx
  public/pages/EditFeatures/components/CategoryField/CategoryField.tsx
  public/pages/EditFeatures/components/CategoryField/__tests__/CategoryField.test.tsx
  public/pages/EditFeatures/components/CategoryField/__tests__/__snapshots__/CategoryField.test.tsx.snap
  public/pages/EditFeatures/containers/EditFeatures.tsx
  public/pages/EditFeatures/containers/utils/formikToFeatures.ts
  public/pages/EditFeatures/utils/helpers.ts
  public/utils/utils.tsx
Labels: enhancement

#315 added the order for the plugin placement in revised kibana side menu
  index.js
Labels: enhancement

#317 bump AD Kibana plugin version to 1.11.0
  .github/workflows/e2e-tests-workflow.yml
  package.json
Labels: version upgrade

#319 Clear model configuration if detector index is changed
  public/pages/createDetector/containers/CreateDetector.tsx
  public/pages/createDetector/containers/DataSource/DataSource.tsx
  public/pages/createDetector/containers/utils/helpers.tsx
Labels: enhancement

#314 Add UX support for HC detector
  package.json
  public/models/interfaces.ts
  public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
  public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
  public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
  public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
  public/pages/AnomalyCharts/containers/AnomalyOccurrenceChart.tsx
  public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
  public/pages/AnomalyCharts/containers/__tests__/AnomaliesChart.test.tsx
  public/pages/AnomalyCharts/containers/__tests__/FeatureBreakDown.test.tsx
  public/pages/AnomalyCharts/utils/anomalyChartUtils.ts
  public/pages/AnomalyCharts/utils/constants.ts
  public/pages/DetectorDetail/containers/DetectorDetail.tsx
  public/pages/DetectorResults/containers/AnomalyHistory.tsx
  public/pages/DetectorResults/containers/AnomalyResults.tsx
  public/pages/DetectorResults/containers/AnomalyResultsTable.tsx
  public/pages/DetectorResults/index.scss
  public/pages/DetectorResults/utils/tableUtils.ts
  public/pages/EditFeatures/components/AggregationSelector/AggregationSelector.tsx
  public/pages/EditFeatures/components/FeatureAccordion/FeatureAccordion.tsx
  public/pages/EditFeatures/containers/EditFeatures.tsx
  public/pages/EditFeatures/containers/SampleAnomalies.tsx
  public/pages/EditFeatures/containers/utils/formikToFeatures.ts
  public/pages/EditFeatures/utils/helpers.ts
  public/pages/createDetector/components/DataFilters/dataFilter.scss
  public/pages/createDetector/containers/CreateDetector.tsx
  public/pages/utils/anomalyResultUtils.ts
  public/redux/reducers/alerting.ts
  public/redux/reducers/anomalyResults.ts
  public/redux/reducers/index.ts
  public/redux/reducers/previewAnomalies.ts
  public/utils/utils.tsx
  server/models/interfaces.ts
  server/models/types.ts
  server/routes/ad.ts
  server/routes/utils/__tests__/adHelpers.test.ts
  server/routes/utils/adHelpers.ts
  test/setup.jest.ts
  yarn.lock
Labels: feature

#318 Add release notes for 1.11.0.0
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.11.0.0.md
Labels: documentation

#324 Add match and count APIs
  public/pages/createDetector/containers/CreateDetector.tsx
  public/redux/reducers/ad.ts
  server/cluster/ad/adPlugin.ts
  server/routes/ad.ts
Labels: enhancement

#325 Fix broken UT when doing duplicate name validation
  public/pages/SampleData/utils/helpers.tsx
  public/pages/createDetector/containers/__tests__/CreateDetector.test.tsx
Labels: test

#327 Show second for heatmap cell hover timestamp
  public/pages/AnomalyCharts/utils/anomalyChartUtils.ts
Labels: bug
