Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2020-11, with the labels that each got.

#332 Fix sunburst chart height is 0
  public/pages/Dashboard/Components/AnomaliesDistribution.tsx
Labels: bug

#334 Fix vulnerability caused by old version formik. Issue: #333
  package.json
  public/pages/EditFeatures/components/CategoryField/__tests__/__snapshots__/CategoryField.test.tsx.snap
  public/pages/createDetector/components/DetectorInfo/utils/__tests__/validation.test.ts
  public/pages/createDetector/components/DetectorInfo/utils/validation.ts
  public/pages/createDetector/containers/CreateDetector.tsx
  yarn.lock
Labels: enhancement

#336 Add release notes
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.12.0.0.md
Labels: documentation
