Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2020-09, with the labels that each got.

#272 Add sample detectors and indices
  public/components/ContentPanel/ContentPanel.tsx
  public/components/CreateDetectorButtons/CreateDetectorButtons.tsx
  public/pages/Dashboard/Components/EmptyDashboard/EmptyDashboard.tsx
  public/pages/Dashboard/Components/EmptyDashboard/__tests__/__snapshots__/EmptyDashboard.test.tsx.snap
  public/pages/DetectorResults/containers/AnomalyResults.tsx
  public/pages/DetectorsList/components/EmptyMessage/EmptyMessage.tsx
  public/pages/DetectorsList/components/EmptyMessage/__tests__/__snapshots__/EmptyMessage.test.tsx.snap
  public/pages/SampleData/components/SampleDataBox/SampleDataBox.tsx
  public/pages/SampleData/components/SampleDataBox/__tests__/SampleDataBox.test.tsx
  public/pages/SampleData/components/SampleDataBox/__tests__/__snapshots__/SampleDataBox.test.tsx.snap
  public/pages/SampleData/components/SampleDataCallout/SampleDataCallout.tsx
  public/pages/SampleData/components/SampleDataCallout/__tests__/SampleDataCallout.test.tsx
  public/pages/SampleData/components/SampleDataCallout/__tests__/__snapshots__/SampleDataCallout.test.tsx.snap
  public/pages/SampleData/components/SampleDetailsFlyout/SampleDetailsFlyout.tsx
  public/pages/SampleData/components/SampleIndexDetailsCallout/SampleIndexDetailsCallout.tsx
  public/pages/SampleData/containers/SampleData/SampleData.tsx
  public/pages/SampleData/containers/SampleData/__tests__/SampleData.test.tsx
  public/pages/SampleData/containers/SampleData/__tests__/__snapshots__/SampleData.test.tsx.snap
  public/pages/SampleData/index.ts
  public/pages/SampleData/utils/constants.tsx
  public/pages/SampleData/utils/helpers.tsx
  public/pages/createDetector/containers/CreateDetector.tsx
  public/pages/createDetector/containers/__tests__/__snapshots__/CreateDetector.test.tsx.snap
  public/pages/main/Main.tsx
  public/pages/utils/SideBar.tsx
  public/pages/utils/constants.ts
  public/redux/reducers/elasticsearch.ts
  public/redux/reducers/sampleData.ts
  public/utils/constants.ts
  server/plugin.ts
  server/routes/ad.ts
  server/routes/elasticsearch.ts
  server/routes/sampleData.ts
  server/sampleData/rawData/ecommerce.json.gz
  server/sampleData/rawData/hostHealth.json.gz
  server/sampleData/rawData/httpResponses.json.gz
  server/sampleData/utils/helpers.ts
  utils/constants.ts
Labels: feature

#296 Update 1.10.0.0 release notes
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.10.0.0.md
Labels: documentation

#297 Make elastic/charts imports more generic
  public/pages/Dashboard/Components/AnomaliesDistribution.tsx
Labels: bug

#298 Fix broken cypress test related to new empty dashboard buttons
  .cypress/integration/ad/dashboard/ad_dashboard.spec.ts
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.10.0.0.md
Labels: test

#300 Fix initialization callouts to properly show when first loading anomaly results page
  public/pages/DetectorResults/containers/AnomalyResults.tsx
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.10.0.0.md
Labels: bug

#301 Fix bug where undefined is shown on UI for estimatedMins in case of ingestion data missing
  public/pages/DetectorResults/containers/AnomalyResults.tsx
Labels: bug

#306 Updating plugin to use Kibana 7.9.1
  .github/workflows/CD.yml
  .github/workflows/e2e-tests-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  package.json
Labels: version upgrade

#308 Updating release notes for ODFE 1.10.1
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.10.0.0.md
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.10.1.0.md
Labels: documentation
