Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2020-06, with the labels that each got.

#226 Automate release notes generation on pushes to master
  .github/draft-release-notes-config.yml
  .github/workflows/CD.yml
  .github/workflows/draft-release-notes-workflow.yml
Labels: documentation

#230 Make all callouts optional on batch action modals
  public/pages/DetectorsList/components/ListActions/ListActions.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/ConfirmDeleteDetectorsModal.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/ConfirmStartDetectorsModal.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/ConfirmStopDetectorsModal.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmDeleteDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/__tests__/ConfirmStopDetectorsModal.test.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/utils/helpers.tsx
  public/pages/DetectorsList/containers/List/List.tsx
  public/pages/DetectorsList/utils/helpers.ts
Labels: enhancement

#233 Rename 'last updated time' to 'last enabled time' on Detector list
  public/models/interfaces.ts
  public/pages/DetectorsList/containers/List/__tests__/List.test.tsx
  public/pages/DetectorsList/utils/tableUtils.tsx
  server/routes/ad.ts
  server/routes/utils/adHelpers.ts
Labels: enhancement

#234 Add Cypress tests for dashboard and detector list
  .cypress/fixtures/delete_detector_response.json
  .cypress/fixtures/multiple_detectors_response.json
  .cypress/fixtures/single_running_detector_response.json
  .cypress/fixtures/single_stopped_detector_response.json
  .cypress/fixtures/start_detector_response.json
  .cypress/fixtures/stop_detector_response.json
  .cypress/integration/ad/dashboard/ad_dashboard.spec.ts
  .cypress/integration/ad/detectorList/detector_list.spec.ts
  .cypress/support/commands.ts
  .cypress/support/index.d.ts
  .cypress/utils/constants.ts
  public/pages/Dashboard/Container/DashboardOverview.tsx
  public/pages/DetectorsList/components/ListActions/ListActions.tsx
  public/pages/DetectorsList/components/ListFilters/ListFilters.tsx
  public/pages/DetectorsList/containers/ConfirmActionModals/ConfirmDeleteDetectorsModal.tsx
  public/pages/DetectorsList/containers/List/List.tsx
Labels: test

#208 Add CI for e2e
  .github/workflows/e2e-tests-workflow.yml
  package.json
Labels: test

#235 Add delete actions UT and fix snapshots
  public/pages/DetectorsList/components/ListActions/__tests__/ListActions.test.tsx
  public/pages/DetectorsList/components/ListActions/__tests__/__snapshots__/ListActions.test.tsx.snap
  public/pages/DetectorsList/components/ListFilters/__tests__/__snapshots__/ListFilters.test.tsx.snap
Labels: test

#239 Bump Kibana compatibility to 7.8.0
  .github/workflows/CD.yml
  .github/workflows/e2e-tests-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  README.md
  package.json
  public/pages/AnomalyCharts/components/AlertsFlyout/__tests__/__snapshots__/AlertsFlyout.test.tsx.snap
  yarn.lock
Labels: odfe-release, version upgrade

#241 Move plugin into Kibana app category
  index.js
Labels: version upgrade

#243 Add finalized 1.9.0.0 release notes
  release-notes/opendistro-for-elasticsearch.anomaly-detection-kibana.release-notes-1.9.0.0.md
Labels: documentation

#246 Add brace dependency
  package.json
  yarn.lock
Labels: dependencies

#247 Fix default filter query when creating detector
  public/pages/createDetector/containers/utils/constant.ts
Labels: bug fix
