Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2021-01, with the labels that each got.

#354 Backport original PR 350: Refactor AnomalyHistory Chart to improve performance for HC detector.
  package.json
  public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
  public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
  public/pages/AnomalyCharts/containers/__tests__/AnomaliesChart.test.tsx
  public/pages/AnomalyCharts/containers/__tests__/AnomalyDetailsChart.test.tsx
  public/pages/AnomalyCharts/containers/__tests__/AnomalyHeatmapChart.test.tsx
  public/pages/AnomalyCharts/containers/__tests__/AnomalyOccurrenceChart.test.tsx
  public/pages/AnomalyCharts/containers/__tests__/__snapshots__/AnomalyHeatmapChart.test.tsx.snap
  public/pages/AnomalyCharts/utils/anomalyChartUtils.ts
  public/pages/Dashboard/utils/utils.tsx
  public/pages/DetectorResults/containers/AnomalyHistory.tsx
  public/pages/utils/__tests__/constants.ts
  public/pages/utils/anomalyResultUtils.ts
  public/pages/utils/constants.ts
  server/models/interfaces.ts
  server/routes/ad.ts
  server/utils/constants.ts
  yarn.lock
Labels: enhancement

#356 Change default shingle size for HC detector to 4
  public/pages/DetectorConfig/containers/Features.tsx
  public/pages/DetectorResults/utils/utils.ts
  public/pages/EditFeatures/components/CategoryField/CategoryField.tsx
  public/pages/EditFeatures/components/CategoryField/__tests__/CategoryField.test.tsx
  public/pages/EditFeatures/containers/EditFeatures.tsx
  public/pages/EditFeatures/utils/helpers.ts
  public/pages/createDetector/containers/utils/__tests__/detectorToFormik.test.ts
  public/pages/createDetector/containers/utils/detectorToFormik.ts
  public/pages/createDetector/containers/utils/helpers.tsx
  public/utils/constants.ts
Labels: enhancement

#358 Update draft release notes config to use URL
  .github/draft-release-notes-config.yml
Labels: documentation

#360 Fix broken unit and integration tests
  .cypress/integration/ad/detectorList/detector_list.spec.ts
  public/pages/CreateHistoricalDetector/components/TimeRange/__tests__/TimeRange.test.tsx
  public/pages/CreateHistoricalDetector/components/TimeRange/__tests__/__snapshots__/TimeRange.test.tsx.snap
  public/pages/HistoricalDetectorDetail/components/__tests__/HistoricalDetectorConfig.test.tsx
  public/pages/HistoricalDetectorDetail/components/__tests__/__snapshots__/HistoricalDetectorConfig.test.tsx.snap
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/__tests__/HistoricalDetectorDetail.test.tsx
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/__tests__/__snapshots__/HistoricalDetectorDetail.test.tsx.snap
Labels: test

#362 Fix live chart bar width
  public/pages/AnomalyCharts/utils/constants.ts
  public/pages/DetectorResults/containers/AnomalyResultsLiveChart.tsx
Labels: bug

#363 Add sleep time before running Cypress tests
  package.json
Labels: test

#364 Add 'No data' state for historical detectors
  public/pages/DetectorsList/utils/helpers.ts
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/HistoricalDetectorDetail.tsx
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/__tests__/HistoricalDetectorDetail.test.tsx
  public/pages/HistoricalDetectorDetail/utils/helpers.tsx
  public/pages/utils/constants.ts
  server/routes/utils/adHelpers.ts
  server/utils/constants.ts
Labels: enhancement

#367 Remove copyright year for newly added files
  public/pages/CreateHistoricalDetector/components/Configuration/Configuration.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/__tests__/Configuration.test.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/ExistingDetectors/ExistingDetectors.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/ExistingDetectors/utils/helpers.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/Features/Features.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/OperationSettings/OperationSettings.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/Timestamp/Timestamp.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/__tests__/ExistingDetectors.test.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/__tests__/Features.test.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/__tests__/OperationSettings.test.tsx
  public/pages/CreateHistoricalDetector/components/Configuration/components/__tests__/Timestamp.test.tsx
  public/pages/CreateHistoricalDetector/components/IndexChooser/IndexChooser.tsx
  public/pages/CreateHistoricalDetector/components/IndexChooser/__tests__/IndexChooser.test.tsx
  public/pages/CreateHistoricalDetector/components/Info/Info.tsx
  public/pages/CreateHistoricalDetector/components/Info/__tests__/Info.test.tsx
  public/pages/CreateHistoricalDetector/components/TimeRange/TimeRange.tsx
  public/pages/CreateHistoricalDetector/components/TimeRange/__tests__/TimeRange.test.tsx
  public/pages/CreateHistoricalDetector/containers/CreateHistoricalDetector.tsx
  public/pages/CreateHistoricalDetector/containers/__tests__/CreateHistoricalDetector.test.tsx
  public/pages/CreateHistoricalDetector/index.ts
  public/pages/CreateHistoricalDetector/utils/constants.ts
  public/pages/CreateHistoricalDetector/utils/helpers.ts
  public/pages/HistoricalDetectorDetail/components/HistoricalDetectorConfig/HistoricalDetectorConfig.tsx
  public/pages/HistoricalDetectorDetail/components/HistoricalDetectorControls/HistoricalDetectorControls.tsx
  public/pages/HistoricalDetectorDetail/components/__tests__/HistoricalDetectorConfig.test.tsx
  public/pages/HistoricalDetectorDetail/components/__tests__/HistoricalDetectorControls.test.tsx
  public/pages/HistoricalDetectorDetail/containers/ActionModals/DeleteHistoricalDetectorModal/DeleteHistoricalDetectorModal.tsx
  public/pages/HistoricalDetectorDetail/containers/ActionModals/EditHistoricalDetectorModal/EditHistoricalDetectorModal.tsx
  public/pages/HistoricalDetectorDetail/containers/ActionModals/__tests__/DeleteHistoricalDetectorModal.test.tsx
  public/pages/HistoricalDetectorDetail/containers/ActionModals/__tests__/EditHistoricalDetectorModal.test.tsx
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/HistoricalDetectorDetail.tsx
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/__tests__/HistoricalDetectorDetail.test.tsx
  public/pages/HistoricalDetectorDetail/index.ts
  public/pages/HistoricalDetectorDetail/utils/constants.tsx
  public/pages/HistoricalDetectorDetail/utils/helpers.tsx
  public/pages/HistoricalDetectorList/components/EmptyHistoricalDetectorMessage/EmptyHistoricalDetectorMessage.tsx
  public/pages/HistoricalDetectorList/components/HistoricalDetectorFilters/HistoricalDetectorFilters.tsx
  public/pages/HistoricalDetectorList/containers/HistoricalDetectorList.tsx
  public/pages/HistoricalDetectorList/containers/__tests__/HistoricalDetectorList.test.tsx
  public/pages/HistoricalDetectorList/index.ts
  public/pages/HistoricalDetectorList/utils/constants.tsx
  public/pages/HistoricalDetectorList/utils/helpers.tsx
Labels: documentation
