Repository opendistro-for-elasticsearch/anomaly-detection-kibana-plugin, pull requests merged in 2021-02, with the labels that each got.

#369 Upgrade to Kibana 7.10.2
  .github/workflows/CD.yml
  .github/workflows/e2e-tests-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  README.md
  kibana.json
  package.json
  yarn.lock
Labels: version upgrade

#311 Change CD workflow to use new staging bucket for artifacts
  .github/workflows/CD.yml
Labels: github actions

#371 Remove stopped annotations for historical detector chart
  public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
Labels: bug

#373 Fix dashboard loading state and empty state logic
  public/pages/Dashboard/Container/DashboardOverview.tsx
Labels: bug

#374 Fix typo in sample eCommerce description
  public/pages/SampleData/containers/SampleData/__tests__/__snapshots__/SampleData.test.tsx.snap
  public/pages/SampleData/utils/constants.tsx
Labels: bug

#368 Simplify historical detector failure states
  public/models/interfaces.ts
  public/pages/DetectorsList/utils/helpers.ts
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/HistoricalDetectorDetail.tsx
  public/pages/HistoricalDetectorDetail/containers/HistoricalDetectorDetail/__tests__/HistoricalDetectorDetail.test.tsx
  public/pages/HistoricalDetectorDetail/utils/helpers.tsx
  public/pages/utils/constants.ts
  server/models/types.ts
  server/routes/ad.ts
  server/routes/utils/__tests__/adHelpers.test.ts
  server/routes/utils/adHelpers.ts
  server/utils/constants.ts
Labels: enhancement

#375 Add release notes for version 1.13.0.0
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.13.0.0.md
Labels: documentation

#376 Fix link to LICENSE.txt
  CONTRIBUTING.md
  release-notes/opendistro-for-elasticsearch-anomaly-detection-kibana-plugin.release-notes-1.13.0.0.md
Labels: documentation

#377 Skip flaky cypress test
  .cypress/integration/ad/workflow/create_detector.spec.ts
Labels: test

#379 Skip other flaky test
  .cypress/integration/ad/detectorList/detector_list.spec.ts
Labels: test

#382 Update default branch in workflows
  .github/workflows/draft-release-notes-workflow.yml
  .github/workflows/e2e-tests-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: github actions
